# Generated by Django 4.0.2 on 2022-10-28 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='name',
        ),
    ]
