# Generated by Django 4.0.4 on 2022-11-05 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_routepoint_customroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='customroute',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customroute',
            name='route_points',
            field=models.ManyToManyField(blank=True, to='app_users.routepoint'),
        ),
    ]
