# Generated by Django 4.0.2 on 2022-11-05 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_customroute_user_alter_customroute_route_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customroute',
            name='route_points',
            field=models.ManyToManyField(blank=True, to='app_users.RoutePoint'),
        ),
        migrations.AlterField(
            model_name='customroute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_routes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
