# Generated by Django 4.0.2 on 2022-11-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0007_alter_customroute_route_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routepoint',
            name='img_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='routepoint',
            name='site_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='routepoint',
            name='ticket_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='routepoint',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
