# Generated by Django 4.0.2 on 2022-11-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='route',
            name='places',
            field=models.ManyToManyField(related_name='route', to='app_main.Place', verbose_name='Места'),
        ),
        migrations.CreateModel(
            name='CustomRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_points', models.ManyToManyField(to='app_main.RoutePoint')),
            ],
        ),
    ]
