# Generated by Django 4.0.4 on 2022-11-05 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_routepoint_alter_route_places_customroute'),
        ('app_main', '0003_route_detail_text'),
    ]

    operations = [
    ]
